format = """
[╭─](bold bright-magenta)$os$username$directory$git_branch$git_status
[╰─](bold bright-magenta)$character"""

[username]
style_user = "bold cyan"
style_root = "bold red"
format = "[$user](bold cyan)[@](bright-magenta)"
show_always = true

[directory]
style = "bold neon"
format = "[ $path ]($style)"
truncation_length = 3

[character]
success_symbol = "[☞⚆‿⚆☞](bold green)"
error_symbol = "[×﹏×](bold red)"

[git_branch]
symbol = " "
style = "bold bright-magenta"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold yellow"

[os]
disabled = true
style = "bold cyan"

[os.synbols]
Linux = "🧠 "
Ubuntu = "🧠 "
